name: PollyGlot CI Pipeline

on:
  workflow_dispatch:
    inputs:
      ec2-name:
        description: Run Terraform code to create an EC2 instance
        required: true
        default: 'Linux Server'
        type: string

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Apply Terraform changes
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      # Save Terraform Outputs
      - name: Save Terraform Outputs
        id: tf_outputs
        run: |
          terraform output -json > tf_outputs.json
          echo "EC2_PUBLIC_IP=$(jq -r '.instance_ip.value' tf_outputs.json)" >> $GITHUB_ENV
          echo "PRIVATE_KEY=$(jq -r '.private_key_pem.value' tf_outputs.json)" >> $GITHUB_ENV
        shell: bash